set(_CATKIN_CURRENT_PACKAGE "seer")
set(seer_VERSION "0.0.0")
set(seer_MAINTAINER "Manash <mpdmanash@gmail.com>")
set(seer_PACKAGE_FORMAT "1")
set(seer_BUILD_DEPENDS "roscpp" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport" "message_generation")
set(seer_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport" "message_runtime")
set(seer_BUILDTOOL_DEPENDS "catkin")
set(seer_BUILDTOOL_EXPORT_DEPENDS )
set(seer_EXEC_DEPENDS "roscpp" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport" "message_runtime")
set(seer_RUN_DEPENDS "roscpp" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport" "message_runtime")
set(seer_TEST_DEPENDS )
set(seer_DOC_DEPENDS )
set(seer_DEPRECATED "")